---
fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-vcs-permalinks
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]

  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.29.3
    hooks:
      - id: check-github-workflows
        name: Check github workflows format

  - repo: https://github.com/markdownlint/markdownlint
    rev: v0.13.0
    hooks:
      - id: markdownlint
        args: [--rules, "~MD013,~MD033,~MD007"]

  - repo: local
    hooks:
      - id: eslint
        name: Typescript linter
        language: system
        entry: cd infra/ && yarn lint
        files: \.ts$
