---
name: "Pull Request Labeler"
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  triage:
    name: Triage
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - name: Labeler
        uses: actions/labeler@main
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
