---
name: "Checks, linters and formatters"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          filter: devopsdays-photos/*

      - name: Use Node.js
        uses: actions/setup-node@v4.0.4
        with:
          node-version: 20
          cache: 'yarn'

      - name: (Install) Install dependencies
        run: |
          yarn install --frozen-lockfile
          cd infra/ && yarn install --frozen-lockfile

      - name: Run pre-commit hooks
        uses: pre-commit/action@v3.0.1
